node {
    docker.image('maven:3.9.0').inside('-v /root/.m2:/root/.m2') {
        stage('Build') {
            sh 'mvn -B -DskipTests clean package'
        }
        stage('Test') {
            sh 'mvn test'
            junit 'target/surefire-reports/*.xml'
        }
        stage('Deploy') {
            input message: 'Lanjutkan ke tahap Deploy?',
                ok: 'Proceed',
                cancel: 'Abort'

            if (params.input == 'Proceed') {
                withCredentials([[
                    $class: 'UsernamePasswordMultiBinding',
                    credentialsId: 'eaeeb0eb-d969-420f-83ae-553e2aba3d53',
                    usernameVariable: 'HEROKU_EMAIL',
                    passwordVariable: 'HEROKU_API_KEY'
                ]]) {
                    sh '''
                        heroku login -i
                        heroku container:login
                        heroku git:remote -a submission-cicd-pipeline-midor
                        heroku ps:scale web=1
                        heroku container:push my-app
                        heroku container:release my-app
                    '''
                }
            }

            sleep 60

            echo 'Application is now running on Heroku.'
        }
    }
}
