node {
    docker.image('maven:3.9.0').inside('-v /root/.m2:/root/.m2') {
        stage('Build') {
            sh 'mvn -B -DskipTests clean package'
        }
        stage('Test') {
            sh 'mvn test'
            junit 'target/surefire-reports/*.xml'
        }
        stage('Deploy') {
            withCredentials([string(credentialsId: '50868197-9178-4ff6-a9c8-36d509564558', variable: 'HEROKU_API_KEY')]) {
                sh 'curl https://cli-assets.heroku.com/install.sh | sh' // Install Heroku CLI
                sh 'heroku container:login'
                sh 'heroku container:push web --app submission-cicd-pipeline-midor'
                sh 'heroku container:release web --app submission-cicd-pipeline-midor'
            }
            sleep 60 // Tunggu sejenak setelah deployment selesai
            echo 'Application is now running on staging server.'
        }
    }
}
